(()=>{
'use strict';
const M=LotteryModel,$=s=>document.querySelector(s),app=$('#app'),overlay=$('#overlay');
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Number(n).toFixed(2),img=(name,cls='icon')=>`<img class="${cls}" src="assets/${name}" alt="">`;
const btn=(text,action,cls='',extra='')=>`<button class="${cls}" data-action="${action}" ${extra}>${text}</button>`;
const storageKey='ig-official-mobile-prototype-v1';let saved={};try{saved=JSON.parse(localStorage.getItem(storageKey)||'{}')}catch{}
let state={family:'pk10',game:'一分赛车',play:0,sub:0,selected:[],unit:1,mult:1,cart:[],records:[],chases:[],favorites:['pk10:4'],balance:10000,theme:false,historyExpanded:false,...saved,page:'gamePage',filter:'全部',recordGame:'全部彩种',seconds:165,period:5107780,sealed:false,manual:[],hot:{},miss:{}};
let pending=null,toastTimer=null,recordPage=0;
function persist(){const {balance,cart,records,chases,favorites,theme}=state;try{localStorage.setItem(storageKey,JSON.stringify({balance,cart,records,chases,favorites,theme}))}catch{}}
function baseCfg(){return M.configs[state.family][state.play]}
function config(){const c={...baseCfg(),rows:[...baseCfg().rows]};if(state.family==='x115'&&state.play===5){c.choose=state.sub+2;c.prize=[6,19,78,540,90,26,9][state.sub]}if(state.family==='x115'&&[0,1].includes(state.play)&&state.sub===1){c.rows=['选号'];c.mode='choose';c.choose=state.play===0?3:2;c.prize=state.play===0?326:109}if(state.family==='x115'&&state.sub===2)c.unsupported=true;return c}
function selectionReset(){state.selected=config().rows.map(()=>[]);state.manual=[];state.hot={};state.miss={}}
function selections(){return config().rows.map((_,i)=>state.selected[i]||[])}
function count(){return state.manual.length||M.count(selections(),config())}
function total(){return M.amount(count(),state.mult,state.unit)}
function gameName(){return state.family==='ssc'?state.game+'时时彩':state.family==='x115'?state.game+'11选5':state.game}
function clock(){return state.sealed?'封盘':`${String(Math.floor(state.seconds/60)).padStart(2,'0')}:${String(state.seconds%60).padStart(2,'0')}`}
function balls(values){return `<span class="balls">${values.map(n=>`<span class="ball b${n}">${n}</span>`).join('')}</span>`}
function resultValues(offset=0){const a=state.family==='pk10'?[1,7,3,10,6,9,4,2,5,8]:state.family==='x115'?[3,9,5,1,6]:state.family==='k3'?[1,5,6]:state.family==='3d'?[3,8,2]:[8,7,0,5,7];return a.map((_,i)=>a[(i+offset)%a.length])}
function top(title,opts={}){return `<header class="top">${opts.logo?'<span class="spacer"></span>':btn(img('return_icon.svg'),'back','back','aria-label="返回"')}${opts.logo?img('IG_logo.png','logo'):btn(esc(title)+(opts.game?'⌄':''),opts.game?'lobby':'noop','title')}${opts.game?`<div class="icons">${btn(img('trend_icon.svg'),'toggleHistory','trend-toggle '+(state.historyExpanded?'active':''),`aria-label="${state.historyExpanded?'收起':'展开'}历史开奖" aria-expanded="${state.historyExpanded}"`)}${btn(img('help_icon.svg'),'help','','aria-label="玩法说明"')}${btn(img('menu_icon.svg'),'menu','','aria-label="菜单"')}</div>`:opts.logo?btn(img('menu_icon.svg'),'menu','','aria-label="菜单"'):'<span style="width:25px"></span>'}</header>`}
function go(page){close();if(location.hash==='#'+page){state.page=page;render()}else location.hash=page}
function render(){document.body.classList.toggle('dark',state.theme);app.innerHTML=`<section class="screen">${state.page==='gamePage'?game():state.page==='gameMenuPage'?lobby():state.page==='basketPage'?basket():state.page==='betRecordPage'?records():state.page==='historyPage'?historyPage():state.page==='reportPage'?report():state.page==='chasePage'?chases():state.page==='trendPage'?trend():state.page==='favoritesPage'?favorites():rules()}</section>`;updateSummary()}
function historyPanel(){const history=Array.from({length:7},(_,i)=>({period:state.period-i-1,values:resultValues(i+1),time:`${String(1+i).padStart(2,'0')}:${String((15+i*7)%60).padStart(2,'0')}`}));return `<section class="quick-history" aria-label="历史开奖结果"><div class="quick-history-head"><div class="quick-history-title"><span class="quick-history-kicker">开奖历史</span><strong>最近 7 期</strong></div>${btn('⌃','toggleHistory','','aria-label="收起历史开奖"')}</div><div class="quick-history-table"><div class="quick-history-row quick-history-label"><span class="quick-period-label">期号／时间</span><span class="quick-balls-label">开奖号码</span></div>${history.map(r=>`<div class="quick-history-row"><span class="quick-period"><b>${String(r.period).slice(-6)}</b><small>${r.time}</small></span><span class="quick-balls">${r.values.map(n=>`<i class="ball b${n}">${n}</i>`).join('')}</span></div>`).join('')}</div><div class="quick-history-footer"><span><i class="live-dot"></i>实时同步 · 以官方开奖为准</span>${btn(img('trend_icon.svg')+'<span>走势</span><b>›</b>','trend','quick-trend')}</div></section>`}
function game(){const cfg=config();return top(gameName(),{game:true})+(state.historyExpanded?historyPanel():'')+`<div class="results"><div class="result-line"><strong>${state.period-1} 期</strong>${balls(resultValues())}${btn(img('trend_icon.svg'),'trend','trend-btn','aria-label="走势图"')}</div><div class="account-line"><strong>${state.period} 期</strong><span>封盘:　<b id="countdown">${clock()}</b></span><span>余额:　<b>${money(state.balance)}</b></span><span>今日:　<b>0.000</b></span></div></div><nav class="nav-row"><span class="edge left">◀</span><div class="nav-scroll" id="plays">${M.configs[state.family].map((p,i)=>btn(p.label,'play',i===state.play?'active':'',`data-index="${i}"`)).join('')}</div><span class="edge">▶</span></nav><nav class="nav-row secondary"><div class="nav-scroll">${(cfg.subs||[state.family==='ssc'||state.family==='3d'?'直选复式':cfg.label]).map((t,i)=>btn(t,'sub',state.sub===i?'active':'',`data-index="${i}"`)).join('')}</div></nav><div class="bet-scroll">${cfg.unsupported?'<div class="empty">此玩法的细项尚待原站逐项核对。<br>请切换其他玩法进行操作演示。</div>':cfg.rows.map((r,i)=>numberRow(r,i,cfg)).join('')}${stakebar()}${state.manual.length?`<div class="badge">已录入 ${state.manual.length} 注号码</div>`:''}</div><footer class="footer"><div class="summary" id="summary"></div><div class="actions">${btn(cfg.rows.length>1?'手工<br>录入':'重置',cfg.rows.length>1?'manual':'reset','outline')}${btn('机选','random','outline')}${btn('直接投注','bet','primary direct')}<span class="or">或</span>${btn('加入号码篮','add','primary add')}${btn(img('basket_icon.svg')+`<b id="cart-count">${state.cart.length}</b>`,'basket','basket-icon','aria-label="号码篮"')}</div></footer>`}
function numberRow(label,i,cfg){return `<section class="pick-row" data-row="${i}"><div class="row-tools"><span class="row-label">${label}</span>${['全','大','小','单','双','清'].map(t=>btn(t,'quick','',`data-row="${i}" data-value="${t}" aria-label="${label}${t}"`)).join('')}</div><div class="numbers-area"><div class="indicators"><label><input type="checkbox" data-stat="hot" data-row="${i}" ${state.hot[i]?'checked':''}>冷热</label><label><input type="checkbox" data-stat="miss" data-row="${i}" ${state.miss[i]?'checked':''}>遗漏</label></div><div class="number-grid">${cfg.values.map((n,j)=>`<div class="number-cell">${btn(esc(n),'number','number '+((state.selected[i]||[]).includes(n)?'selected':''),`data-row="${i}" data-index="${j}" aria-label="${label} ${n}" aria-pressed="${(state.selected[i]||[]).includes(n)}" ${String(n).length>2?'style="font-size:11px;width:100%;border-radius:6px"':''}`)}${state.hot[i]?`<span class="stat">${(j*3+i+7)%19}</span>`:''}${state.miss[i]?`<span class="stat" style="color:#888">${(j*7+i+3)%24}</span>`:''}</div>`).join('')}</div></div></section>`}
function stakebar(){return `<div class="stakebar"><div class="stepper">${btn('−','minus','','aria-label="减少倍数"')}<input id="multiplier" aria-label="投注倍数" type="number" min="1" max="99999" value="${state.mult}" inputmode="numeric"><span>倍</span>${btn('+','plus','','aria-label="增加倍数"')}</div>${['元','角','分'].map((t,i)=>btn(t,'unit','unit '+(state.unit===[1,.1,.01][i]?'active':''),`data-value="${[1,.1,.01][i]}"`)).join('')}</div>`}
function updateSummary(){if($('#summary'))$('#summary').innerHTML=`玩法奖金: <em>${config().prize}</em> 元 <em>${count()}</em> 注 <em>${money(total())}</em> 元 <em>${money(count()?config().prize*state.mult*state.unit:0)}</em> 元`;if($('#cart-count'))$('#cart-count').textContent=state.cart.length}
function refreshPicks(){const sc=$('.bet-scroll'),scroll=sc?.scrollTop||0;const pscroll=$('#plays')?.scrollLeft||0;render();if($('.bet-scroll'))$('.bet-scroll').scrollTop=scroll;if($('#plays'))$('#plays').scrollLeft=pscroll}
function lobby(){return top('',{logo:true})+`<div class="lobby"><div class="banner"></div><div class="section-heading">${img('collect_icon.svg')}我的收藏 ${btn(img('redact_icon.svg'),'favorites','edit','aria-label="编辑收藏"')}</div><div class="favorites">${state.favorites.map(key=>{const [fam,index]=key.split(':'),g=M.groups.find(x=>x.id===fam);return btn(img(g.icon)+`<span>${esc(g.games[index])}</span><small>02:15</small>`,'openGame','favorite',`data-family="${fam}" data-index="${index}"`)}).join('')}${btn(img('unnamed.png')+'<span>添加收藏</span>','favorites','favorite')}</div><div class="section-heading">${img('funnel_icon.svg')}游戏列表</div>${M.groups.map(g=>`<section class="lobby-group"><div class="group-icon">${img(g.icon)}</div><div class="game-grid">${g.games.map((name,i)=>btn(`<span>${esc(name)}</span><small>${name==='福彩3D'||name==='排列五'?'关盘':i%3===0?'00:59':i%3===1?'01:14':'02:14'}</small>`,'openGame','game-card',`data-family="${g.id}" data-index="${i}"`)).join('')}</div></section>`).join('')}<div class="badge">手机交互原型 · 模拟数据</div></div>`}
function favorites(){return top('编辑我的收藏')+`<div class="content"><p class="hint" style="margin:18px">点选彩种添加或取消收藏，最多 5 个。</p>${M.groups.map(g=>`<section class="lobby-group"><div class="group-icon">${img(g.icon)}</div><div class="game-grid">${g.games.map((n,i)=>btn(esc(n),'favorite','game-card '+(state.favorites.includes(g.id+':'+i)?'chosen':''),`data-family="${g.id}" data-index="${i}"`)).join('')}</div></section>`).join('')}</div><div class="basket-footer">${btn('完成','lobby','primary')}</div>`}
function itemDescription(item){return item.manual?.length?item.manual.map(r=>r.join(' ')).join('；'):item.rows.map((row,i)=>`${item.labels[i]}: ${row.join(',')||'—'}`).join(' / ')}
function ticket(){return {id:Date.now()+'-'+Math.random().toString(16).slice(2),game:gameName(),family:state.family,play:config().label,sub:config().subs?.[state.sub]||'',rows:selections().map(r=>[...r]),labels:[...config().rows],manual:state.manual.map(r=>[...r]),count:count(),unit:state.unit,mult:state.mult,amount:total(),period:state.period}}
function cartTotal(){return Math.round(state.cart.reduce((sum,x)=>sum+x.amount,0)*100)/100}
function basket(){return top('号码篮')+`<div class="content">${state.cart.length?state.cart.map((r,i)=>`<article class="record"><header><strong>${esc(r.game)} · ${esc(r.play)}</strong>${btn('×','remove','','data-index="'+i+'" aria-label="删除第'+(i+1)+'条"')}</header><div class="details">${esc(itemDescription(r))}</div><div class="row"><span>${r.count} 注 · ${r.mult} 倍 · ${r.unit===1?'元':r.unit===.1?'角':'分'}</span><strong>${money(r.amount)} 元</strong></div></article>`).join(''):'<div class="empty">号码篮暂无号码</div>'}<label class="checkline"><input id="chase-enabled" type="checkbox">追号投注</label><div id="chase-options" hidden class="filter-panel"><label class="field">追多少期 <input id="chase-count" type="number" value="5" min="2" max="50" inputmode="numeric"></label><label><input id="stop-win" type="checkbox" checked>中奖后停止追号</label><p class="hint">演示计划，不会自动发送任何投注。</p></div></div><div class="basket-footer"><div class="summary">共 ${state.cart.length} 条　${state.cart.reduce((n,r)=>n+r.count,0)} 注　合计 <em>${money(cartTotal())}</em> 元</div>${btn('继续选号','game','outline')}${btn('清空号码篮','clearCart','outline')}${btn('一键投注','betCart','primary','style="grid-column:1/-1"')}</div>`}
function records(){let rows=state.records.filter(r=>(state.filter==='全部'||r.status===state.filter)&&(state.recordGame==='全部彩种'||r.game===state.recordGame));const pages=Math.ceil(rows.length/10);recordPage=Math.min(recordPage,Math.max(0,pages-1));return top('投注记录')+`<div class="content"><div class="filter-panel"><p class="hint">此处可查询未开奖与当日的全部注单，其余注单请往[${btn('历史报表','report')}]中查询。</p><select id="record-game" class="select" aria-label="彩种筛选">${['全部彩种',...new Set(state.records.map(r=>r.game))].map(n=>`<option ${n===state.recordGame?'selected':''}>${esc(n)}</option>`).join('')}</select><div class="filters">${['全部','未开奖','中奖','未中奖','已撤单'].map(n=>btn(n,'filter',state.filter===n?'active':'',`data-value="${n}"`)).join('')}</div></div>${rows.slice(recordPage*10,(recordPage+1)*10).map(r=>`<article class="record"><header>${esc(r.game)}<span>${r.status}</span></header><div>${esc(r.play)} · ${r.period} 期</div><div class="details">${esc(itemDescription(r))}</div><div class="row"><span>${r.count} 注 / ${r.mult} 倍</span><b>${money(r.amount)} 元</b></div><div class="row details"><time>${esc(r.time)}</time>${r.status==='未开奖'?btn('撤单','cancelRecord','',`data-id="${r.id}"`):''}</div></article>`).join('')}<div class="pagination">${btn('≪','firstPage','',recordPage===0?'disabled':'')}${btn('〈','prevPage','',recordPage===0?'disabled':'')}<span>${rows.length?recordPage+1:0}/${pages}</span>${btn('〉','nextPage','',recordPage>=pages-1?'disabled':'')}${btn('≫','lastPage','',recordPage>=pages-1?'disabled':'')}</div></div>`}
function historyPage(){return top('开奖结果')+`<div class="content"><div class="filter-panel"><select id="history-game" class="select" aria-label="开奖彩种">${M.groups.flatMap(g=>g.games.map((n,i)=>`<option value="${g.id}:${i}" ${g.id===state.family&&n===state.game?'selected':''}>${esc(n+(g.id==='ssc'?'时时彩':g.id==='x115'?'11选5':''))}</option>`)).join('')}</select></div>${Array.from({length:20},(_,i)=>`<div class="history-row"><time>${state.period-i-1} 期</time>${balls(resultValues(i))}</div>`).join('')}<div class="badge">以上为离线演示开奖结果</div></div>`}
function report(){const live=state.records.filter(r=>r.status!=='已撤单'),sum=live.reduce((n,r)=>n+r.amount,0);return top('历史报表')+`<div class="content"><div class="filter-panel"><label class="field">查询日期<input type="date" id="report-date" value="${new Date().toLocaleDateString('en-CA')}"></label>${btn('查询','queryReport','primary','style="width:100%"')}</div><div id="report-result"><div class="stat-grid"><div>投注金额<strong>${money(sum)}</strong></div><div>中奖金额<strong>0.00</strong></div><div>有效注单<strong>${live.length}</strong></div><div>已结算盈亏<strong>0.00</strong></div></div><div class="badge">仅统计本机模拟注单；未开奖金额不计入盈亏。</div></div></div>`}
function chases(){return top('追号记录')+`<div class="content">${state.chases.length?state.chases.map(r=>`<article class="record"><header>追号计划 ${r.id.slice(-6)}<span>${r.status}</span></header><div>${esc(r.game)} · ${r.period} 期起</div><div>${r.periods} 期　每期 ${money(r.perPeriod)} 元</div><div>总额 ${money(r.amount)} 元</div><div class="details">${r.stopWin?'中奖后停止追号':'不自动停止'} · 原型计划</div>${r.status==='待执行'?btn('停止追号','stopChase','outline',`data-id="${r.id}"`):''}</article>`).join(''):'<div class="empty">暂无追号记录<br><small>可在号码篮中创建模拟追号计划</small></div>'}</div>`}
function trend(){return top('走势 · '+gameName())+`<div class="content"><div class="badge">冠军 / 第一位走势 · 模拟数据</div><table class="trend-table"><thead><tr><th>期号</th>${M.range(state.family==='pk10'||state.family==='x115'?1:0,state.family==='x115'?11:state.family==='pk10'?10:9).map(n=>`<th>${n}</th>`).join('')}</tr></thead><tbody>${Array.from({length:25},(_,i)=>`<tr><td>${state.period-i-1}</td>${M.range(state.family==='pk10'||state.family==='x115'?1:0,state.family==='x115'?11:state.family==='pk10'?10:9).map(n=>`<td class="${resultValues(i)[0]===n?'hit':''}">${resultValues(i)[0]===n?n:(i+n)%12}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function rules(){return top('游戏规则')+`<div class="content rules"><h3>${esc(gameName())} · ${esc(config().label)}</h3><p>${ruleText()}</p><h3>投注操作</h3><p>选择号码后，可调整倍数及元、角、分。每注基础金额为 2 元，角模式为 0.2 元，分模式为 0.02 元。</p><p>可直接确认模拟投注，也可将多个选号方案加入号码篮后统一确认。</p><h3>演示范围</h3><p>本原型使用独立模拟余额、期号、倒计时和开奖记录。号码与统计资料仅供功能评审。奖金未逐项核对的玩法仅作演示；正式规则以产品需求及服务端配置为准。</p><p>尚未核对的复杂玩法不开放提交，避免将不确定规则交付为正式需求。</p></div>`}
function ruleText(){const c=config();return state.family==='pk10'?(c.mode==='sum'?'选择任意位置的号码，所选号码与相应位置的开奖号码一致，即符合中奖条件。':'竞猜'+c.rows.join('、')+'，投注号码须与对应位置的开奖号码一致。不同名次不可出现相同号码。'):c.mode==='choose'?`选择至少 ${c.choose} 个号码，系统按组合计算注数。`:c.mode==='sum'?'选择一个或多个投注号码，按选中的号码分别计注。':'各位置至少选择一个号码，按所有有效组合计算注数。'}
function close(){overlay.innerHTML='';pending=null}
function dialog(title,body,actions=[{label:'关闭',action:'close'}]){overlay.innerHTML=`<div class="overlay"><section class="dialog" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="dialog-head">${title}</div><div class="dialog-body">${body}</div><div class="dialog-actions">${actions.map(a=>btn(a.label,a.action,a.action==='close'&&actions.length>1?'outline':'primary')).join('')}</div></section></div>`;overlay.querySelector('button')?.focus()}
function notify(message){dialog('提示',esc(message))}
function toast(message){$('#toast').textContent=message;$('#toast').className='toast';clearTimeout(toastTimer);toastTimer=setTimeout(()=>{$('#toast').className='';$('#toast').textContent=''},1800)}
function menu(){const items=[['开奖结果','history','IGicon_kjjg.svg'],['投注记录','records','IGicon_tzjl.svg'],['追号记录','chases','IGicon_zhjl.svg'],['历史报表','report','IGicon_lsbb.svg'],['游戏规则','rules','IGicon_yxgz.svg'],['开奖官网','official','IGicon_kjlogo.svg'],['更换皮肤','theme','IGicon_bright.svg'],['新版彩票','newVersion','IGicon_xbcp.svg']];overlay.innerHTML=`<div class="overlay" data-backdrop><aside class="drawer" role="dialog" aria-label="功能菜单"><button class="close-drawer" data-action="close" aria-label="关闭菜单">×</button><div class="avatar"></div><div class="user">demo01 ～ A 盘</div><div class="drawer-grid">${items.map(([n,a,f])=>btn(img(f)+n,a)).join('')}</div><div class="prototype-note">手机原型 · 数据仅保存在本机<br>${btn('演示设置','settings','','style="color:#fe6318;margin-top:12px"')}</div></aside></div>`}
function openGame(family,index){const g=M.groups.find(g=>g.id===family),name=g.games[index];if(['福彩3D','排列五'].includes(name)){notify('当前游戏已关盘');return}state.family=family;state.game=name;state.play=0;state.sub=0;state.mult=1;state.unit=1;selectionReset();go('gamePage')}
function validate(){if(config().unsupported){notify('此玩法尚待核对，暂不开放模拟投注');return false}if(!count()){notify('请选择有效号码！每个必选位置需选择号码，不同名次不能重复。');return false}return true}
function confirmTickets(items,chase=null){if(state.sealed){notify('当前游戏已封盘');return}const amount=Math.round(items.reduce((n,r)=>n+r.amount,0)*(chase?.periods||1)*100)/100;if(!items.length){notify('请添加号码！');return}if(amount>state.balance){notify('余额不足，请调整投注金额');return}dialog(chase?'确认追号':'投注确认',`<dl><dt>彩种</dt><dd>${esc([...new Set(items.map(x=>x.game))].join('、'))}</dd><dt>期号</dt><dd>${state.period}</dd><dt>注数</dt><dd>${items.reduce((n,r)=>n+r.count,0)} 注${chase?' × '+chase.periods+' 期':''}</dd><dt>金额</dt><dd style="color:var(--orange)">${money(amount)} 元</dd></dl><p style="font-size:11px;color:#999;margin-bottom:0">模拟投注，不产生真实交易</p>`,[{label:'取消',action:'close'},{label:'确认',action:'confirmBet'}]);pending={items:JSON.parse(JSON.stringify(items)),amount,chase,period:state.period,fromCart:state.page==='basketPage'}}
function submit(){if(!pending)return;const p=pending;if(state.sealed||p.period!==state.period){notify('当前期次已封盘，请重新确认');return}if(p.amount>state.balance){notify('余额不足');return}state.balance=Math.round((state.balance-p.amount)*100)/100;if(p.chase){state.chases.unshift({id:Date.now().toString(),game:p.items.map(x=>x.game).join('、'),period:p.period,periods:p.chase.periods,perPeriod:p.amount/p.chase.periods,amount:p.amount,stopWin:p.chase.stopWin,status:'待执行'})}else{state.records.unshift(...p.items.map(r=>({...r,id:Date.now()+'-'+Math.random().toString(16).slice(2),period:p.period,status:'未开奖',time:new Date().toLocaleString('zh-CN',{hour12:false})})))}if(p.fromCart)state.cart=[];selectionReset();persist();close();render();dialog('提示',p.chase?'模拟追号计划已建立':'模拟投注成功！', [{label:'查看记录',action:p.chase?'chases':'records'},{label:'关闭',action:'close'}])}
function onAction(e){const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,i=Number(b.dataset.index),r=Number(b.dataset.row),v=b.dataset.value;
switch(a){case'noop':break;case'back':go(state.page==='gamePage'?'gameMenuPage':'gamePage');break;case'lobby':go('gameMenuPage');break;case'game':go('gamePage');break;case'menu':menu();break;case'close':close();break;case'openGame':openGame(b.dataset.family,i);break;case'favorites':go('favoritesPage');break;case'favorite':{const key=b.dataset.family+':'+i;if(state.favorites.includes(key))state.favorites=state.favorites.filter(x=>x!==key);else if(state.favorites.length<5)state.favorites.push(key);else{toast('最多收藏 5 个彩种');break}persist();render();break}
case'play':{const x=$('#plays').scrollLeft;state.play=i;state.sub=0;selectionReset();render();$('#plays').scrollLeft=x;break}case'sub':state.sub=i;selectionReset();refreshPicks();break;
case'number':{state.manual=[];const n=config().values[i];state.selected[r]||=[];state.selected[r]=state.selected[r].includes(n)?state.selected[r].filter(x=>x!==n):[...state.selected[r],n];refreshPicks();break}
case'quick':{state.manual=[];const vals=config().values,mid=(Number(vals[0])+Number(vals[vals.length-1]))/2;state.selected[r]=v==='清'?[]:vals.filter(n=>v==='全'||v==='大'&&Number(n)>mid||v==='小'&&Number(n)<=mid||v==='单'&&Number(n)%2===1||v==='双'&&Number(n)%2===0);refreshPicks();break}
case'reset':selectionReset();state.mult=1;state.unit=1;refreshPicks();break;
case'random':{const c=config();if(c.unsupported){notify('此玩法尚待核对');break}selectionReset();let pool=[...c.values];if(c.mode==='choose'){for(let x=0;x<c.choose;x++){const ix=Math.floor(Math.random()*pool.length);state.selected[0].push(pool.splice(ix,1)[0])}}else{state.selected=c.rows.map(()=>{const ix=Math.floor(Math.random()*pool.length),n=pool[ix];if(c.mode==='unique')pool.splice(ix,1);return[n]})}refreshPicks();break}
case'plus':state.mult=Math.min(99999,state.mult+1);$('#multiplier').value=state.mult;updateSummary();break;case'minus':state.mult=Math.max(1,state.mult-1);$('#multiplier').value=state.mult;updateSummary();break;case'unit':state.unit=Number(v);refreshPicks();break;
case'add':if(validate()){state.cart.push(ticket());selectionReset();persist();refreshPicks();toast('已加入号码篮')}break;
case'basket':state.cart.length?go('basketPage'):notify('请添加号码!');break;case'remove':state.cart.splice(i,1);persist();render();break;case'clearCart':dialog('提示','确定清空号码篮？',[{label:'取消',action:'close'},{label:'清空',action:'doClear'}]);break;case'doClear':state.cart=[];persist();close();render();break;
case'bet':if(validate())confirmTickets([ticket()]);break;case'betCart':{let chase=null;if($('#chase-enabled')?.checked){const periods=Number($('#chase-count').value);if(!Number.isInteger(periods)||periods<2||periods>50){notify('追号期数须为 2–50 的整数');break}chase={periods,stopWin:$('#stop-win').checked}}confirmTickets(state.cart,chase);break}case'confirmBet':submit();break;
case'records':state.filter='全部';state.recordGame='全部彩种';recordPage=0;go('betRecordPage');break;case'filter':state.filter=v;recordPage=0;render();break;case'firstPage':recordPage=0;render();break;case'prevPage':recordPage--;render();break;case'nextPage':recordPage++;render();break;case'lastPage':recordPage=999999;render();break;
case'cancelRecord':{const rec=state.records.find(x=>x.id===b.dataset.id);dialog('撤单确认',`撤销此模拟注单并退还 ${money(rec.amount)} 元？`,[{label:'取消',action:'close'},{label:'确认撤单',action:'doCancel'}]);pending={cancelId:rec.id};break}case'doCancel':{const rec=state.records.find(x=>x.id===pending?.cancelId);if(rec?.status==='未开奖'){rec.status='已撤单';state.balance=Math.round((state.balance+rec.amount)*100)/100;persist()}close();render();toast('已撤单');break}
case'history':go('historyPage');break;case'report':go('reportPage');break;case'chases':go('chasePage');break;case'trend':go('trendPage');break;case'toggleHistory':state.historyExpanded=!state.historyExpanded;render();break;case'rules':go('rulesPage');break;case'help':dialog('玩法说明',`<b>${esc(config().label)}</b><p>${ruleText()}</p><small>玩法奖金：${config().prize} 元（演示）</small>`);break;
case'theme':state.theme=!state.theme;persist();close();render();toast(state.theme?'已切换深色皮肤':'已切换明亮皮肤');break;
case'official':dialog('开奖官网','原型保留此入口；正式开奖来源及外链由技术接入。');break;case'newVersion':dialog('新版彩票','本次复刻范围为原站橘色手机版。新版彩票为独立产品入口。');break;
case'stopChase':{const x=state.chases.find(x=>x.id===b.dataset.id);if(x.status==='待执行'){x.status='已停止';state.balance=Math.round((state.balance+x.amount)*100)/100;persist();render();toast('已停止计划，模拟金额已退回')}break}
case'queryReport':{const date=$('#report-date').value;if(date!==new Date().toLocaleDateString('en-CA'))$('#report-result').innerHTML='<div class="empty">该日期暂无模拟记录</div>';else render();toast('查询完成');break}
case'manual':dialog('手工录入',`<p style="font-size:12px">每行一注，共 ${config().rows.length} 个号码，以空格或逗号分隔。重复行会自动去重。</p><textarea id="manual-text" aria-label="手工号码" placeholder="例如：${config().rows.map((_,i)=>config().values[i%config().values.length]).join(' ')}"></textarea>`,[{label:'取消',action:'close'},{label:'确认录入',action:'applyManual'}]);break;
case'applyManual':{const c=config(),text=$('#manual-text').value.trim();if(!['unique','product'].includes(c.mode)){notify('此玩法请使用点选号码');break}const lines=text.split(/\n|;/).filter(Boolean).map(l=>l.trim().split(/[\s,，]+/).map(Number));if(!lines.length||lines.some(row=>row.length!==c.rows.length||row.some(n=>!c.values.includes(n))||c.mode==='unique'&&new Set(row).size!==row.length)){notify('号码格式不正确，请检查每行数量、号码范围及重复号码');break}state.manual=[...new Map(lines.map(r=>[r.join(','),r])).values()];state.selected=c.rows.map(()=>[]);close();refreshPicks();break}
case'settings':dialog('原型演示设置',`<p>所有资料保存在本机，不连接正式服务。</p><label class="field">模拟余额 <input id="demo-balance" type="number" min="0" max="99999999" value="${state.balance}"></label><label class="field"><input id="demo-sealed" type="checkbox" ${state.sealed?'checked':''} style="width:auto">模拟封盘</label>`,[{label:'取消',action:'close'},{label:'套用',action:'applySettings'}]);break;
case'applySettings':{const n=Number($('#demo-balance').value);if(!Number.isFinite(n)||n<0||n>99999999){notify('请输入 0–99999999 的模拟余额');break}state.balance=Math.round(n*100)/100;state.sealed=$('#demo-sealed').checked;state.seconds=state.sealed?0:165;persist();close();render();break}
}}
document.addEventListener('click',onAction);
document.addEventListener('input',e=>{if(e.target.id==='multiplier'){const n=Number(e.target.value);state.mult=Number.isFinite(n)?Math.min(99999,Math.max(1,Math.floor(n))):1;updateSummary()}});
document.addEventListener('change',e=>{const t=e.target;if(t.dataset.stat){state[t.dataset.stat][Number(t.dataset.row)]=t.checked;refreshPicks()}if(t.id==='multiplier'){const n=Number(t.value);state.mult=Number.isFinite(n)?Math.min(99999,Math.max(1,Math.floor(n))):1;t.value=state.mult;updateSummary()}if(t.id==='chase-enabled')$('#chase-options').hidden=!t.checked;if(t.id==='record-game'){state.recordGame=t.value;recordPage=0;render()}if(t.id==='history-game'){const [fam,i]=t.value.split(':');state.family=fam;state.game=M.groups.find(g=>g.id===fam).games[Number(i)];state.play=0;state.sub=0;selectionReset();render()}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});overlay.addEventListener('click',e=>{if(e.target.matches('[data-backdrop]'))close()});
window.addEventListener('hashchange',()=>{const valid=['gamePage','gameMenuPage','basketPage','betRecordPage','historyPage','reportPage','chasePage','trendPage','favoritesPage','rulesPage'];state.page=valid.includes(location.hash.slice(1))?location.hash.slice(1):'gamePage';close();render()});
setInterval(()=>{if(!state.sealed&&state.seconds>0){state.seconds--;if(!state.seconds)state.sealed=true}if($('#countdown'))$('#countdown').textContent=clock()},1000);
selectionReset();state.page=location.hash.slice(1)||'gamePage';render();
})();
